version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=albion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  rediscache:
    image: bitnami/redis:6.0
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - '6379:6379'

volumes:
  db_data: {}
